import type { PlaceCategory } from "./place";

const SIGHTSEEING_TYPES: string[] = [
  "tourist_attraction",
  "museum",
  "art_gallery",
  "art_museum",
  "history_museum",
  "park",
  "national_park",
  "state_park",
  "botanical_garden",
  "garden",
  "castle",
  "cultural_landmark",
  "historical_landmark",
  "historical_place",
  "monument",
  "fountain",
  "sculpture",
  "scenic_spot",
  "beach",
  "mountain_peak",
  "nature_preserve",
  "island",
  "lake",
  "river",
  "woods",
  "plaza",
  "planetarium",
  "visitor_center",
  "church",
  "buddhist_temple",
  "hindu_temple",
  "mosque",
  "shinto_shrine",
  "synagogue",
  "performing_arts_theater",
];

const FOOD_TYPES: string[] = [
  "restaurant",
  "cafe",
  "bakery",
  "bar",
  "coffee_shop",
  "tea_house",
  "pub",
  "bistro",
  "diner",
  "buffet_restaurant",
  "fast_food_restaurant",
  "fine_dining_restaurant",
  "food_court",
  "brunch_restaurant",
  "breakfast_restaurant",
  "dessert_restaurant",
  "dessert_shop",
  "ice_cream_shop",
  "donut_shop",
  "juice_shop",
  "noodle_shop",
  "ramen_restaurant",
  "sushi_restaurant",
  "seafood_restaurant",
  "steak_house",
  "pizza_restaurant",
  "hamburger_restaurant",
  "sandwich_shop",
  "snack_bar",
  "deli",
  "cafeteria",
  "meal_delivery",
  "meal_takeaway",
  "bar_and_grill",
  "beer_garden",
  "brewery",
  "brewpub",
  "cocktail_bar",
  "lounge_bar",
  "wine_bar",
  "sports_bar",
  "hookah_bar",
  "gastropub",
  "winery",
  "american_restaurant",
  "chinese_restaurant",
  "french_restaurant",
  "indian_restaurant",
  "italian_restaurant",
  "japanese_restaurant",
  "korean_restaurant",
  "korean_barbecue_restaurant",
  "mexican_restaurant",
  "thai_restaurant",
  "vietnamese_restaurant",
  "mediterranean_restaurant",
  "middle_eastern_restaurant",
  "greek_restaurant",
  "spanish_restaurant",
  "turkish_restaurant",
  "indonesian_restaurant",
  "lebanese_restaurant",
  "brazilian_restaurant",
];

const SHOPPING_TYPES: string[] = [
  "shopping_mall",
  "store",
  "supermarket",
  "clothing_store",
  "book_store",
  "market",
  "department_store",
  "convenience_store",
  "gift_shop",
  "grocery_store",
  "flea_market",
  "farmers_market",
  "electronics_store",
  "cosmetics_store",
  "jewelry_store",
  "shoe_store",
  "sporting_goods_store",
  "home_goods_store",
  "furniture_store",
  "pet_store",
  "toy_store",
  "liquor_store",
  "thrift_store",
  "discount_store",
  "food_store",
];

const TRANSPORT_TYPES: string[] = [
  "airport",
  "international_airport",
  "train_station",
  "bus_station",
  "bus_stop",
  "subway_station",
  "transit_station",
  "transit_stop",
  "light_rail_station",
  "tram_stop",
  "ferry_terminal",
  "ferry_service",
  "taxi_stand",
  "taxi_service",
  "park_and_ride",
  "bike_sharing_station",
];

const ACCOMMODATION_TYPES: string[] = [
  "hotel",
  "lodging",
  "hostel",
  "motel",
  "resort_hotel",
  "bed_and_breakfast",
  "guest_house",
  "inn",
  "campground",
  "cottage",
  "farmstay",
  "japanese_inn",
  "budget_japanese_inn",
  "extended_stay_hotel",
  "rv_park",
];

const ACTIVITY_TYPES: string[] = [
  "amusement_park",
  "stadium",
  "gym",
  "fitness_center",
  "aquarium",
  "zoo",
  "wildlife_park",
  "water_park",
  "ski_resort",
  "golf_course",
  "bowling_alley",
  "movie_theater",
  "night_club",
  "karaoke",
  "casino",
  "spa",
  "concert_hall",
  "opera_house",
  "cultural_center",
  "community_center",
  "event_venue",
  "live_music_venue",
  "hiking_area",
  "observation_deck",
  "swimming_pool",
  "ice_skating_rink",
  "adventure_sports_center",
  "amusement_center",
  "sports_complex",
  "arena",
  "video_arcade",
  "miniature_golf_course",
  "ferris_wheel",
  "roller_coaster",
];

const CATEGORY_LOOKUP: Map<string, PlaceCategory> = new Map(
  [
    ...SIGHTSEEING_TYPES.map((t) => [t, "sightseeing"] as const),
    ...FOOD_TYPES.map((t) => [t, "food"] as const),
    ...SHOPPING_TYPES.map((t) => [t, "shopping"] as const),
    ...TRANSPORT_TYPES.map((t) => [t, "transport"] as const),
    ...ACCOMMODATION_TYPES.map((t) => [t, "accommodation"] as const),
    ...ACTIVITY_TYPES.map((t) => [t, "activity"] as const),
  ],
);

export function toPlaceCategory(googleType: string | null | undefined): PlaceCategory {
  if (!googleType) {
    return "other";
  }
  return CATEGORY_LOOKUP.get(googleType) ?? "other";
}
